version: '3.1'

services:

  mongo-test:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  
  vault-test:
    image: vault
    ports:
      - 3000:8200
    volumes:
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      VAULT_LOCAL_CONFIG: >-
        {
          "backend": {
            "file": {
              "path": "/vault/data"
            }
          },
          "listener": {
            "tcp":{
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          },
          "ui": true
        }
    command: server
    cap_add:
      - IPC_LOCK